
let activities = [
  {
    id: 1,
    name: "Yoga Class",
    description: "Morning Yoga Session",
    privacy: "public",
    creator: 1,
    participants: [2, 3],
    date: "2024-09-08",
  },
  {
    id: 2,
    name: "Coding Workshop",
    description: "Learn Node.js",
    privacy: "private",
    creator: 2,
    participants: [1, 4],
    date: "2024-09-10",
  },
  {
    id: 3,
    name: "Hiking Trip",
    description: "Group hike through the hills",
    privacy: "public",
    creator: 3,
    participants: [2, 5, 6],
    date: "2024-09-15",
  },
  {
    id: 4,
    name: "Book Club",
    description: "Discuss the latest bestseller",
    privacy: "private",
    creator: 4,
    participants: [1, 2, 7],
    date: "2024-09-12",
  },
  {
    id: 5,
    name: "Cooking Class",
    description: "Learn to cook Italian dishes",
    privacy: "public",
    creator: 5,
    participants: [3, 8, 9],
    date: "2024-09-20",
  },
  {
    id: 6,
    name: "Photography Walk",
    description: "Capture nature shots",
    privacy: "public",
    creator: 6,
    participants: [2, 4, 10],
    date: "2024-09-18",
  },
  {
    id: 7,
    name: "Football Match",
    description: "Friendly soccer match at the park",
    privacy: "private",
    creator: 7,
    participants: [5, 6, 11],
    date: "2024-09-19",
  },
  {
    id: 8,
    name: "Art Exhibition",
    description: "Visit the local art gallery",
    privacy: "public",
    creator: 8,
    participants: [9, 3],
    date: "2024-09-14",
  },
  {
    id: 9,
    name: "Tech Meetup",
    description: "Discuss the latest in tech",
    privacy: "private",
    creator: 9,
    participants: [1, 4, 5],
    date: "2024-09-22",
  },
  {
    id: 10,
    name: "Gardening Workshop",
    description: "Learn about plant care",
    privacy: "public",
    creator: 10,
    participants: [7, 8],
    date: "2024-09-25",
  },
  {
    id: 11,
    name: "Chess Tournament",
    description: "Join a chess competition",
    privacy: "private",
    creator: 11,
    participants: [2, 6, 9],
    date: "2024-09-23",
  },
  {
    id: 12,
    name: "Movie Night",
    description: "Watch a popular film together",
    privacy: "public",
    creator: 12,
    participants: [1, 3, 7],
    date: "2024-09-24",
  },
];

module.exports = activities;
